url: https://vvitohu.github.io
baseurl: 
# Site settings
title: Dev Diaries
email: otis.vito@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: 胡勝紘
  pic: 1
  position: Lead Designer
  social:
    - title: Instagram
      url: https://www.instagram.com/otis.vito/
    - title: facebook
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Instagram
    url: https://www.instagram.com/otis.vito/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: github
    url: https://github.com/vvitohu
  - title: github
    url: https://github.com/vvitohu

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

collections:
  onshape:
    output: true
    permalink: /onshape/:path/